version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.2
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  wazuh:
    image: wazuh/wazuh:4.1.4
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
    volumes:
      - ./wazuh/config:/var/ossec/etc
      - ./wazuh/data:/var/ossec/data
